version: 1.0.{build}
image: Visual Studio 2017
environment:
  DeployExtension: false
configuration: Release
before_build:
- ps: nuget restore src -Verbosity quiet
build:
  verbosity: minimal
test: off
