version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
environment:
  VisualStudioVersion: 15.0
  DeployExtension: false
configuration: Release
before_build:
- ps: nuget restore src -Verbosity quiet
build:
  verbosity: minimal
test: off
artifacts:
- path: bin\Release\Microsoft.VisualStudio.LanguageServices.Lua.vsix
  name: Lua Language service
- path: bin\%configuration%\LuaDebuggerLauncher.vsix
  name: Lua Debugger launcher
